language: python
dist: precise

# Python releases to test
python:
  - 3.6

# Django releases
env:
  - DJANGO_VERSION=2.0.3

# Package installation
install:
  - pip install django~=$DJANGO_VERSION
  - python setup.py install

# Run the tests
script:
  - python tests/manage.py test example
