language: python
dist: precise

# Python releases to test
python:
  - 2.6
  - 2.7
  - 3.3

# Django releases
env:
  - DJANGO_VERSION=Django>=1.5
  - DJANGO_VERSION=Django>=1.11

# Package installation
install:
  - export DJANGO_SETTINGS_MODULE=mysite.settings
  - pip install $DJANGO_VERSION
  - python setup.py install
  - pip install djangoajax
  - pip freeze djangoajax

# Run the tests
script:
  - python setup.py test
