language: python

python:
  - 3.5
  - 3.6

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

env:
  - DJANGO_VERSION=2.0.8

install:
  - pip install django~=$DJANGO_VERSION
  - python setup.py install

script:
  - python tests/manage.py test example
