language: python
dist: precise

# Python releases to test
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

# Django releases
env:
  - DJANGO_VERSION=1.7.0
  - DJANGO_VERSION=1.9.0
  - DJANGO_VERSION=1.11.0

# Package installation
install:
  - pip install decorator
  - pip install django-appconf~=1.0.0
  - pip install django-jenkins
  - pip install django~=$DJANGO_VERSION
  - python setup.py install

# Run the tests
script:
  - python tests/manage.py test example

matrix:
    exclude:
        - python: 3.5
          env: DJANGO_VERSION=1.7.0
        - python: 3.3
          env: DJANGO_VERSION=1.9.0
