language: python
dist: precise

# Python releases to test
python:
  - 2.6
  - 2.7
  - 3.3

# Django releases
env:
  - DJANGO_VERSION=Django==1.5.12
  - DJANGO_VERSION=Django==1.6.10
  - DJANGO_VERSION=Django==1.7.5
  - DJANGO_VERSION=Django==1.8.0
  - DJANGO_VERSION=Django==1.9.0

# Package installation
install:
  - pip install $DJANGO_VERSION
  - python setup.py install
  - pip install djangoajax
  - pip freeze djang bvoajax

# Run the tests
script:
  - python setup.py test
